language: node_js

node_js: ['6', '7', '8', '9', '10']

install:
- yarn install

script:
- yarn lint
- yarn build
- yarn test

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}" > ~/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish .
  on:
    tags: true
    node: '8'

notifications:
  email:
    tomkaczocha@gmail.com
